name: Deploy and Run VRP_TW

on:
    push:
        branches:
          - 'main'

jobs:
    deploy_and_run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.10.12

            - name: Install dependencies
              run: pip3 install --upgrade --user ortools;pip3 install requests

            - name: Get Credentials
              env:
                GITHUB_TOKEN: ${{ secrets.API_KEY }}
              run:
                echo $GITHUB_TOKEN > API_KEY_HOLDER.env

            - name: Run Matrix Creation
              run: sudo chmod +x ./*.py;./route_matrices.py
            
            - name: Run CVRP
              run: sudo chmod +x ./*.py;./vrp_tw.py

            - name: Remove Credentials
              run: rm API_KEY_HOLDER.env